/**
 * AIInsightCard — Explainable AI (XAI) Decision Insight
 *
 * Renders the natural-language explanation produced by the backend's
 * xaiService, translating the raw rule-engine output (score, DTI, rules
 * triggered) into a plain-English underwriting summary for the business
 * user. Styling reacts to the decision outcome so risk teams get an
 * immediate visual signal alongside the text:
 *   - APPROVED → soft green border/background
 *   - REJECTED → amber/red border/background
 */
export default function AIInsightCard({ explanation, decision, source, model, isLoading }) {
  const approved = decision?.toLowerCase() === 'approved';

  const palette = approved
    ? {
        border: 'rgba(52,211,153,0.3)',
        bg: 'linear-gradient(135deg, rgba(6,30,22,0.75) 0%, rgba(16,50,38,0.55) 100%)',
        glow: 'rgba(52,211,153,0.12)',
        accent: '#34d399',
        chipBg: 'rgba(52,211,153,0.12)',
        chipBorder: 'rgba(52,211,153,0.3)',
      }
    : {
        border: 'rgba(251,191,36,0.3)',
        bg: 'linear-gradient(135deg, rgba(46,26,6,0.75) 0%, rgba(56,20,15,0.55) 100%)',
        glow: 'rgba(248,113,113,0.12)',
        accent: '#fbbf24',
        chipBg: 'rgba(248,113,113,0.12)',
        chipBorder: 'rgba(248,113,113,0.3)',
      };

  return (
    <section
      className="relative rounded-xl p-6 md:p-8 overflow-hidden"
      style={{
        background: palette.bg,
        border: `1px solid ${palette.border}`,
        backdropFilter: 'blur(16px)',
      }}
    >
      {/* Ambient glow accent */}
      <div
        className="absolute -top-16 -right-16 w-56 h-56 rounded-full pointer-events-none"
        style={{ background: `radial-gradient(circle, ${palette.glow} 0%, transparent 70%)`, filter: 'blur(30px)' }}
      />

      <div className="relative flex items-start justify-between gap-4 mb-4 flex-wrap">
        <div className="flex items-center gap-3">
          <div
            className="w-10 h-10 rounded-lg flex items-center justify-center flex-shrink-0"
            style={{ background: palette.chipBg, border: `1px solid ${palette.chipBorder}` }}
          >
            <span className="material-symbols-outlined text-lg" style={{ color: palette.accent }}>
              auto_awesome
            </span>
          </div>
          <div>
            <h3 className="text-base md:text-lg font-semibold" style={{ color: '#dae2fd' }}>
              ✨ Explainable AI Decision Insight
            </h3>
            <p className="text-[11px]" style={{ color: '#908fa0' }}>
              Plain-language underwriting summary, generated for auditability
            </p>
          </div>
        </div>

        {!isLoading && source && (
          <span
            className="flex-shrink-0 px-2.5 py-1 rounded-full text-[10px] font-bold tracking-widest uppercase border"
            style={{ background: palette.chipBg, color: palette.accent, borderColor: palette.chipBorder }}
          >
            {source === 'llm' ? 'Local LLM' : 'Rule-Based NLG'}
          </span>
        )}
      </div>

      {isLoading ? (
        <div className="space-y-2.5 animate-pulse">
          <div className="h-3 rounded-full w-full" style={{ background: 'rgba(255,255,255,0.08)' }} />
          <div className="h-3 rounded-full w-[92%]" style={{ background: 'rgba(255,255,255,0.08)' }} />
          <div className="h-3 rounded-full w-[76%]" style={{ background: 'rgba(255,255,255,0.08)' }} />
        </div>
      ) : explanation ? (
        <p className="text-sm md:text-[15px] leading-relaxed" style={{ color: '#c7c4d7' }}>
          {explanation}
        </p>
      ) : (
        <p className="text-sm italic" style={{ color: '#908fa0' }}>
          No AI-generated explanation is available for this application.
        </p>
      )}

      {!isLoading && model && (
        <div
          className="relative mt-5 pt-4 flex items-center gap-2"
          style={{ borderTop: '1px solid rgba(255,255,255,0.06)' }}
        >
          <span className="material-symbols-outlined text-sm" style={{ color: '#464554' }}>
            verified_user
          </span>
          <p className="text-[10px] font-mono" style={{ color: '#464554' }}>
            Generated by {model} — decision logic remains fully rule-based &amp; auditable
          </p>
        </div>
      )}
    </section>
  );
}
