const PDFDocument = require("pdfkit");

// Generates a loan assessment PDF and pipes it directly to the HTTP response.
// PDFKit works as a stream — we write sections top to bottom like a document.
const generateLoanPDF = (res, applicant, applicantId) => {
  const doc = new PDFDocument({ margin: 50 });

  // Tell the browser to download this as a PDF file
  res.setHeader("Content-Type", "application/pdf");
  res.setHeader("Content-Disposition", `attachment; filename=loan-report-${applicantId}.pdf`);

  // Pipe the PDF stream directly into the HTTP response
  doc.pipe(res);

  // ─── HEADER ──────────────────────────────────────────────────────────────
  doc.fontSize(20).font("Helvetica-Bold").text("Loan Approval Assessment Report", { align: "center" });
  doc.moveDown(0.5);
  doc.fontSize(10).font("Helvetica").fillColor("gray").text("Confidential — For Internal Use Only", { align: "center" });
  doc.fillColor("black");
  doc.moveDown(1);
  doc.moveTo(50, doc.y).lineTo(550, doc.y).stroke();
  doc.moveDown(1);

  // ─── SECTION 1: Applicant Details ────────────────────────────────────────
  sectionTitle(doc, "Applicant Details");
  field(doc, "Applicant ID",         applicant.applicant_id);
  field(doc, "Evaluation Date",      new Date(applicant.created_at).toDateString());
  field(doc, "Monthly Income",       `Rs. ${applicant.monthly_income}`);
  field(doc, "Monthly Expense",      `Rs. ${applicant.monthly_expense}`);
  field(doc, "Existing Loans",       applicant.existing_loans);
  field(doc, "Credit History",       `${applicant.credit_history_months} months`);
  field(doc, "Defaults",             applicant.defaults_count);
  doc.moveDown(1);

  // ─── SECTION 2: Credit Assessment ────────────────────────────────────────
  sectionTitle(doc, "Credit Assessment");
  field(doc, "Credit Score",         applicant.score);
  field(doc, "Decision",             applicant.decision);
  field(doc, "Risk Band",            applicant.risk_band);
  field(doc, "DTI Percentage",       `${applicant.dti_percentage}%`);
  doc.moveDown(1);

  // ─── SECTION 3: Decision Reasons ─────────────────────────────────────────
  // reasons is stored as JSON string in MySQL — parse it back to array
  sectionTitle(doc, "Decision Reasons");
  const reasons = safeParseJSON(applicant.reasons);
  if (reasons.length > 0) {
    reasons.forEach((r) => {
      const icon = r.status === "PASS" ? "✓" : "⚠";
      doc.fontSize(10).font("Helvetica").text(`  ${icon}  ${r.detail}`);
      doc.moveDown(0.3);
    });
  } else {
    doc.fontSize(10).text("  No reasons available.");
  }
  doc.moveDown(1);

  // ─── SECTION 4: Loan Recommendation ──────────────────────────────────────
  sectionTitle(doc, "Loan Recommendation");
  field(doc, "Recommended Loan Amount",    `Rs. ${applicant.recommended_loan_amount}`);
  field(doc, "Affordable EMI",             `Rs. ${applicant.affordable_emi || "N/A"}`);
  field(doc, "Estimated Loan Eligibility", `Rs. ${applicant.estimated_loan_eligibility || "N/A"}`);
  doc.moveDown(1);

  // ─── SECTION 5: AI Underwriting Summary ──────────────────────────────────
  // Natural-language explanation generated by the XAI interpretation layer.
  // Kept as a permanent part of the audit trail so a human reviewer or
  // regulator can see, in plain English, exactly why this decision was made
  // — alongside the raw rule trace in Section 3 above.
  sectionTitle(doc, "AI Underwriting Summary");
  if (applicant.ai_explanation) {
    doc.fontSize(10).font("Helvetica-Oblique").fillColor("#333333").text(
      applicant.ai_explanation,
      { align: "left", width: 500, lineGap: 3 }
    );
    doc.fillColor("black");
    doc.moveDown(0.5);
    doc.fontSize(8).font("Helvetica").fillColor("gray").text(
      `Generated by: ${applicant.ai_explanation_model || "N/A"} (${applicant.ai_explanation_source === "llm" ? "Local LLM Inference" : "Deterministic NLG Fallback"})`
    );
    doc.fillColor("black");
  } else {
    doc.fontSize(10).font("Helvetica-Oblique").fillColor("gray").text(
      "No AI-generated explanation is available for this application."
    );
    doc.fillColor("black");
  }
  doc.moveDown(1);

  // ─── SECTION 6: Audit Information ────────────────────────────────────────
  sectionTitle(doc, "Audit Information");
  field(doc, "Rule Engine Version",  "v1.0");
  field(doc, "Evaluation Timestamp", new Date(applicant.created_at).toISOString());
  doc.moveDown(1);

  // Footer
  doc.moveTo(50, doc.y).lineTo(550, doc.y).stroke();
  doc.moveDown(0.5);
  doc.fontSize(9).fillColor("gray").text("Generated by Loan Approval Engine — Fiserv Hackathon", { align: "center" });

  // Finalize the PDF — this flushes and ends the stream
  doc.end();
};

// ─── HELPERS ─────────────────────────────────────────────────────────────────

// Renders a bold section heading with a light underline
const sectionTitle = (doc, title) => {
  doc.fontSize(13).font("Helvetica-Bold").fillColor("#003366").text(title);
  doc.moveDown(0.3);
  doc.moveTo(50, doc.y).lineTo(550, doc.y).strokeColor("#cccccc").stroke();
  doc.strokeColor("black").fillColor("black");
  doc.moveDown(0.5);
};

// Renders a label: value line
const field = (doc, label, value) => {
  doc.fontSize(10).font("Helvetica-Bold").text(`${label}: `, { continued: true });
  doc.font("Helvetica").text(`${value}`);
  doc.moveDown(0.3);
};

// Safely parse JSON — returns empty array if parsing fails
const safeParseJSON = (value) => {
  try { return JSON.parse(value); }
  catch { return []; }
};

module.exports = { generateLoanPDF };
